# Generated by Django 4.1.4 on 2022-12-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('released', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='covers')),
                ('artist', models.ManyToManyField(to='musicians.artist')),
            ],
        ),
    ]
