# Generated by Django 4.1.4 on 2022-12-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0002_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('released', models.DateField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicians.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.artist')),
                ('lyric', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicians.lyrics')),
            ],
        ),
    ]
