# Generated by Django 4.1.4 on 2022-12-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_lyrics_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lyrics',
            new_name='Lyric',
        ),
    ]
